// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvX1hJnQ8ksHSlCYbaDaV9a2WyeYnAv50',
    appId: '1:707537672788:web:f6a81b97bca7d209daebc1',
    messagingSenderId: '707537672788',
    projectId: 'soares-administradora-condomin',
    authDomain: 'soares-administradora-condomin.firebaseapp.com',
    storageBucket: 'soares-administradora-condomin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWNXD6MiIIqaU5U5eob1NGZhQSCoAEuY0',
    appId: '1:707537672788:android:23060c0026eb1d2ddaebc1',
    messagingSenderId: '707537672788',
    projectId: 'soares-administradora-condomin',
    storageBucket: 'soares-administradora-condomin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsjvNEDX032lNzqzSY9nm13LQSBPiuisQ',
    appId: '1:707537672788:ios:eb6fe23b02ac0f7adaebc1',
    messagingSenderId: '707537672788',
    projectId: 'soares-administradora-condomin',
    storageBucket: 'soares-administradora-condomin.appspot.com',
    iosClientId: '707537672788-s5e24okqjehe1q7fu6n6vk3f1mpbka72.apps.googleusercontent.com',
    iosBundleId: 'com.example.soaresAdministradoraCondominios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsjvNEDX032lNzqzSY9nm13LQSBPiuisQ',
    appId: '1:707537672788:ios:eb6fe23b02ac0f7adaebc1',
    messagingSenderId: '707537672788',
    projectId: 'soares-administradora-condomin',
    storageBucket: 'soares-administradora-condomin.appspot.com',
    iosClientId: '707537672788-s5e24okqjehe1q7fu6n6vk3f1mpbka72.apps.googleusercontent.com',
    iosBundleId: 'com.example.soaresAdministradoraCondominios',
  );
}
